name: Fix Code Style

on:
  push:
    branches: master

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: fix style
        run: pint
      - name: Push Changes Back to Repo
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git diff --staged --quiet || git commit -m "chore: fix code style"
          git push
